include:
  - project: devops/cicd
    ref: stable
    file: templates/sonar.yml
  - project: devops/cicd
    ref: stable
    file: templates/js/preparation.yml
  - project: devops/cicd
    ref: stable
    file: templates/deploy.yml

stages:
  - verification
  - preparation
  - deploy

.default_branch: &default_branch
  only:
    - develop

# override config
.sonar_branch_config:
  <<: *default_branch

.preparation_config:
  <<: *default_branch
  before_script:
    - cp src/environments/environment.deploy.ts src/environments/environment.ts

.deploy_config:
  <<: *default_branch
  tags:
    - insomnograf
    - testing
